@startuml


Jacob -left-> (+Updating Sprite)
Jacob -right-> (Updating UML)
Adam  -left->  (Controler support)
Adam  -right->  (Animations)
Josh  -left->  (Resurching Networking)
Josh  -right->  (Maps)

@enduml
