simple UML example
used PlantUML can info can be found at the following link:
http://plantuml.com/class-diagram

@startuml

package Sprite_Gen <<rect>> {
  class Sprite_Two_Dimensions {
    Base sprite class from which all custom sprites inherit
    ==
    Vars
    --
    + position_x
    + position_y
    + velocity_x
    + velocity_y
    + acceleration_x
    + acceleration_y
    + images = []
    + fixed
    + spawn_area
    ==
    Funtions
    --
    - __inti__(spawn_area, fixed)
    # Functions to send or resive velocirt or position_x
    # if nothing is sent the values will be unchanged
    + Position(*pos = (x,y)) : (x,y)
    + Velocity(*vel = (x,y)) : (x,y)
    + Acceleration(*vos = (x,y)) : (x,y)
    + Locational_Data() : (Position,Velocity,Acceleration)
    #Img functions
    + Load_Image (file_Path, scale, x_res) : img_Count
    + Set_Image(img_Num)

  }
}

package Map_Gen <<rect>> {
  

}
@enduml
